#!/bin/sh

#==========BLACK MAGIC ==========
git diff --staged --name-only |
while IFS= read -r line; do
	python cleaner.py --filepath $line
done
git add --update $(git diff --staged --name-only)
#================================

. git-sh-setup
test -x "$GIT_DIR/hooks/pre-commit" &&
        exec "$GIT_DIR/hooks/pre-commit"
:
